name: check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    container:
      image: ghcr.io/eclipse-ankaios/app-ankaios-dev:0.2.0-rc1
      options: --user root --privileged

    steps:
      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.CONTAINER_REGISTRY_PASSWORD }} | podman login sdvblueprint.azurecr.io --username ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password-stdin
      - run: apt-get update
      - run: apt-get install -y git jq
      - name: install yq
        run: |
          curl -sL https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/bin/yq
          chmod +x /usr/bin/yq
      - name: Tweak git config
        run: |
          git config --global --add safe.directory '*'
          echo "if [ -f /etc/bash_completion ] && ! shopt -oq posix; then\n . /etc/bash_completion \nfi" >> /root/.bashrc
          echo 'export PATH=$PATH:/workspaces/app/scripts:/workspaces/app/in-vehicle-stack/scenarios/smart_trailer_use_case/scripts' >> /root/.bashrc
      - run: mkdir /tmp/logs
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      - name: Start Ankaios
        run: |
          cd eclipse-ankaios/scripts
          ./run_maestro.sh
      - run: ank get workloads
      - name: Start trailer applications
        run: |
          cd in-vehicle-stack/scenarios/smart_trailer_use_case/scripts
          ./start_trailer_applications_ankaios.sh & > /tmp/logs/start_trailer_applications_ankaios.log
      - name: Connect trailer
        run: |
          ank run workload trailer_connected_provider --runtime podman --config $'image: sdvblueprint.azurecr.io/sdvblueprint/in-vehicle-stack/trailer_connected_provider:0.1.0\ncommandOptions: ["--network", "host", "--name", "trailer_connected_provider"]' --agent agent_A
      - run: ank get workloads
      - run: cat /tmp/logs/*.log
